version: "3.7"
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      - FLASK_ENV=dev
    ports:
      - 5000:5000
    volumes:
      - .:/app
    entrypoint:
      - /app/scripts/docker_script.sh


