defaultLootRequest = {
    "hoards": [
{
"q":      "3",
"level":	"1",
"coins":	"1",
"valuables":	"1",
"items":	"1",
},
{
    "q": "5",
    "level": "1",
    "coins": "1",
    "valuables": "1",
    "items": "1",
}
    ],
"gem": "1",
"art":	"1",
"magic":	"1",
"magic_type":	"*",
"magic_armor":	"1",
"magic_weapon":	"1",
"potion":	"1",
"ring":	"1",
"rod":	"1",
"scroll":	"1",
"staff":	"1",
"wand":	"1",
"wondrous_item":	"1",
"universal_item":	"1",
"minor":	"1",
"medium":	"1",
"major":	"1",
"gp_limit":	"0",
}